services:
  - type: web
    name: odoo15
    env: docker
    region: oregon
    plan: starter
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: postgresql://odoouser:iGJ43xbvIf6FgfliB8JLdklE6HAyiOJW@dpg-d253g9re5dus73f7c9a0-a/odoodatabase
        fromService:
          name: odoo-postgres
          type: postgres
          property: host
      - key: odoouser
        fromService:
          name: odoo-postgres
          type: postgres
          property: user
      - key: iGJ43xbvIf6FgfliB8JLdklE6HAyiOJW
        fromService:
          name: odoo-postgres
          type: postgres
          property: password

volumes:
  - name: odoo-data
    mountPath: /opt/odoo/.local/share/Odoo
